### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by Muennighoff** [naver/splade#18]
Maybe a stupid question, but you can't use SPLADE for clustering, right?

**Comment by cadurosar** [comment]
Hey, sorry I thought I had answered this before but it seems that I forgot to send it...

We haven't tried, but this is definitely something that is on our mind. It is still not clear what method, but this should be possible

**Comment by thibault-formal** [comment]
Hi @Muennighoff ,
I close the issue -- let us know if you want additional details.
Thibault
