### ISSUE TITLE
Fine Tuning

### ISSUE THREAD

**Issue by shaileshj2803** [naver/splade#20]
Do you have example of finetuning?

**Comment by thibault-formal** [comment]
Hi @shaileshj2803 ,

What do you mean exactly? Training SPLADE can be seen as "finetuning" (we start from a pre-trained BERT); you have all the steps described in the README. 

If you are looking for actual examples of SPLADE outputs, you can have a look at [inference_splade.ipynb](https://github.com/naver/splade/blob/main/inference_splade.ipynb)

Thibault

**Comment by thibault-formal** [comment]
Let us know if you need more details, in the meantime I close the issue.

Thibault

**Comment by shaileshj2803** [comment]
Sure thanks
