### ISSUE TITLE
Dockerized environment to run splade

### ISSUE THREAD

**Issue by shikharsrivastava** [naver/splade#27]
Can you please provide a Dockerfile to run splade? The conda env has dependencies on binaries built against nvidia-cuda for linux platform. I cannot build it for non-cuda linux and osx. I tried replacing those dependencies with their replacement built for usage with cpu, however, still did not manage to make it work.

A Dockerfile should allow users to use splade more easily across platforms.

**Comment by cadurosar** [comment]
Hi @shikharsrivastava sorry for the delay on answering this, but the main problem for us is a technical one: No one on the team is actually familiar with working with docker. Maybe someone in the community could help getting this out?

**Comment by KevinColemanInc** [comment]
+1, I have spent a few hours trying to run this on my m1 arm macos mac. Still haven't got it to work yet

I am struggling to get this to run on colab too

**Comment by KevinColemanInc** [comment]
I got the python notebook working on my m1.

For future people:
Remove the following from `conda_spade_env.yml`
- all non-`pip` `dependencies`
- nmslib==2.1.1
- onnxruntime==1.11.1
- tbb==2021.6.0
- tbb-devel==2021.6.0

Bump the version
- psutil==5.9.4

Add the pip packages the env
- spacy-transformers
- pip

Add the dependency
- python==3.9

For @cadurosar, would you be open to an MR to update the readme and include an `m1` friendly conda env?

**Comment by cadurosar** [comment]
For sure, this would also help me test on my machine.

**Comment by thibault-formal** [comment]
hi @shikharsrivastava ,
as Carlos said, we are not very familiar with docker. If you feel comfortable, feel free to submit a PR. 
closing the issue for the moment
