### ISSUE TITLE
Training code availability

### ISSUE THREAD

**Issue by hguan6** [naver/splade#3]
When you are going to release the training code? Thank you!

**Comment by thibault-formal** [comment]
Hi,
Sorry for the late answer ! We are currently preparing a code release for the training part - we will let you know when it's ready ! 
Best,
Thibault

**Comment by hguan6** [comment]
Thank you!

**Comment by thibault-formal** [comment]
hi @hguan6 
sorry for the delay, you can find the training code in the `training_with_sentence_transformers` folder
Best,
Thibault
