### ISSUE TITLE
Python version 3.8 or 3.9?

### ISSUE THREAD

**Issue by KevinColemanInc** [naver/splade#30]
The requirements section in the ReadMe.md says `3.9`
https://github.com/naver/splade/blob/main/README.md?plain=1#L55

But conda env says `3.8`
https://github.com/naver/splade/blob/main/conda_splade_env.yml#L128

Which is preferred?

**Comment by cadurosar** [comment]
I would say that 3.8 is preferred, but we have used both. I think me and @thibault-formal discussed a bit on this, but I don't remember, do you remember Thibault?

**Comment by KevinColemanInc** [comment]
I only tried 3.9 on my m1 and it worked.

**Comment by thibault-formal** [comment]
hi,
strange, I don't know why there is this mismatch. From my experience, both are working.

**Comment by thibault-formal** [comment]
we will try to clarify, closing the issue.
