### ISSUE TITLE
Training SPLADE with a smaller dataset?

### ISSUE THREAD

**Issue by Marcus-M1999** [naver/splade#35]
Hello,

Thank you for researching SPLADE & setting up the GitHub REPO in such an easy-to-access way. I am trying to experiment with SPLADE and was wondering if it was possible to use the MSMarco small dataset to train instead of the larger one. I was curious since it was taking ~30 hours/epoch to train with the data from the distli_from_ensemble data config file.

**Comment by thibault-formal** [comment]
hi @Marcus-M1999 

In practice, you can obviously train the model with smaller datasets. 1 epoch on MS MARCO is already quite large, and you can check the validation metrics to assess whether it's useful to train for longer.

best
Thibault

**Comment by thibault-formal** [comment]
Closing the issue!
