### ISSUE TITLE
Running SPLADE in production (Render python server)

### ISSUE THREAD

**Issue by arainey2022** [naver/splade#37]
Hi team, I'm working with my development team on using SPLADE for sparse embeddings (alongside dense embeddings from OpenAI Ada), with the end goal of having a hybrid search setup.

However, we keep running into memory issues creating embeddings for chunks of text.

I was wondering if you have any tips for running this in production or better still if there is an API available that you're aware of that can take text as an input and output spare embeddings?

Any help would be hugely appreciated.

**Comment by thibault-formal** [comment]
hi @arainey2022 ,

We are currently discussing the release of an API for SPLADE. 
Regarding your question, it might just be that your batch size is too large (SPLADE embeddings take a bit more memory than dense embeddings due to the large output space).

**Comment by arainey2022** [comment]
Thank you very much for this!

I would love to be your first API customer! We'd be very interested in a service like this. I don't suppose you have any timelines for this?

Is there a batch size you'd recommend?

And have you seen cases where someone has SPLADE running on a Render/Heroku type of setup?

**Comment by thibault-formal** [comment]
> I would love to be your first API customer! We'd be very interested in a service like this. I don't suppose you have any timelines for this?

Nice to hear! Unfortunately, no timeline yet! 

> Is there a batch size you'd recommend?

The batch size really depends on your hardware.. on a single GPU, it should be easy to have a few hundred documents per batch. 

> And have you seen cases where someone has SPLADE running on a Render/Heroku type of setup?

Not that I am aware of.

**Comment by Sayed-Ameer** [comment]
You can try https://github.com/pinecone-io/pinecone-text/#splade but you have to figure out how to build an index for the output. I just found out about this repo but i would really like if someone can build a searchable index that accept indices, values.

**Comment by arainey2022** [comment]
Thanks Sayed. We're actually trying this library, but having trouble keeping the server from crashing.

**Comment by thibault-formal** [comment]
I am closing this issue, feel free to re-open it if needed!
