### ISSUE TITLE
[Bug] Get PyTorch version

### ISSUE THREAD

**Issue by leobavila** [naver/splade#42]
Hi, I believe there is a bug in the function to check if Pytorch version >= 1.6.

https://github.com/naver/splade/blob/main/splade/tasks/amp.py

```python
import torch

# inspired from Colbert repo: https://github.com/stanford-futuredata/ColBERT

PyTorch_over_1_6 = float((torch.__version__.split('.')[1])) >= 6 and float((torch.__version__.split('.')[0])) >= 1
```
It returns false for a pytorch version '2.0.1+cu117' (google colab). Could you guys check it please?
I have replaced the function by another one:

```python
PyTorch_over_1_6 = float(".".join([torch.__version__.split('.')[0], torch.__version__.split('.')[1]])) >= 1.6
```

Full example:
![image](https://github.com/naver/splade/assets/35712949/6f31d875-9d64-4a6a-8e12-c22e066763f6)

This error makes the code to break when using this pytorch version combined with fp16 = True.

Error message:
"Cannot use AMP for PyTorch version < 1.6"

From:
![image](https://github.com/naver/splade/assets/35712949/a609ad58-9d02-467b-91fd-7282683d18b1)

**Comment by leobavila** [comment]
I have sent a PR to fix it.

**Comment by cadurosar** [comment]
Yes, this was indeed a bug, we had "fixed" in the upcoming version by removing the check, but this is actually better than what we had.

Thanks a lot!

(I'm closing as I merged, but feel free to open if I forgot something)
