### ISSUE TITLE
Whether the SPLADE model supports the distinction of 'is_q'?

### ISSUE THREAD

**Issue by xwang-hub** [naver/splade#48]
I noticed relevant content in the code regarding it, but there is no specific model path provided for 'is_q'.
 
Regards

**Comment by thibault-formal** [comment]
Hi @xyCaicaicai 
SPLADE definitely supports this distinction (having separate query/doc encoders). This is triggered when `model_type_or_dir_q` is defined in the init dict (see for instance: https://github.com/naver/splade/blob/main/conf/train/model/separate_distilbert_mlmflops.yaml) 

You can find a trained model here for instance: https://huggingface.co/naver/efficient-splade-VI-BT-large-doc

Best
