### ISSUE TITLE
Is it possible to get a commercial license? 

### ISSUE THREAD

**Issue by skeptrunedev** [naver/splade#52]
We are a startup who is attempting to sell a new search API with some of the latest open source text embedding and cross-encoder models. We ourselves are BSL-licensed so I totally understand not wanting someone to commercialize your work and give nothing back. 

SPLADE is obviously a very good and well-tested sparse-vector encoder and alternative to BM_25 and we would like to include it in our commercial product if possible. 

**Is there a way to get a commercial license?** We are still a tiny company without much revenue for an outright purchase, but  maybe we could setup some kind of channel partnership? Not sure, but it would be amazing to figure something out if at all possible. Thanks!

**Comment by sclincha** [comment]
Hi @skeptrunedev ,
 Yes it is possible to get a commercial licence. I''ll contact you

**Comment by firebait** [comment]
Hi @sclincha , we have been evaluating the new models and we would like to get some information on purchasing a commercial license. 
We are startup looking to enhance our search product and we think the new models would be a good fit.
We were a bit bummed out that there was no commercial license available until we say this comment. 
So, if you can please reach out to me. My email is in my bio. Looking forward to hearing from you.

**Comment by sclincha** [comment]
Hi @firebait ! Sure I''ll contact you!

**Comment by firebait** [comment]
Thank you @sclincha . As a quick follow up question regarding licensing. We are not planning on training a model we are just looking to use the current pre-trained models. Do those fall under the `Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License` as well?

**Comment by noahfradin** [comment]
Hi @sclincha. We're also a startup in need of a commercial license. We're fans and would like to understand our options. Could you reach out at the email in my bio?

**Comment by kevin4885** [comment]
Hi @sclincha I would like to request a commercial license as well.  Thanks!

**Comment by firebait** [comment]
> Hi @sclincha I would like to request a commercial license as well. Thanks!

I'm not sure how this works. I started conversations with the Korea team and got completely ghosted.
We ended up going with the Elasticsearch Elser model as we already are using elasticsearch so something to consider if you are running a tight deadline. I think Pinecone also has a SPLADE type model.

**Comment by kevin4885** [comment]
I found this as well.

https://huggingface.co/prithivida/Splade_PP_en_v1

**Comment by firebait** [comment]
I've tried a couple of these SPLADE implementations and the results are not that great but you can try it and evaluate. I have not tried this one though. Might be worth it

**Comment by ajassal** [comment]
One more request to see if we can get an agreement for commercial usage. Please connect with me.
We provide collaboration and governance SaaS applications for enterprises, and search is one of the features.
