### ISSUE TITLE
Benchmark Performance After Re-ranking?

### ISSUE THREAD

**Issue by mattare2** [naver/splade#8]
I'm curious if you've run your model with a "second-stage" reranker, on the BEIR benchmarks.
Would you expect much benefit from this?

Thank you, and excellent work!

**Comment by thibault-formal** [comment]
Hi @mattare2 ,
We did not try to use a re-ranker on top of SPLADE on BEIR. I am guessing we would observe some benefit (similarly to BM25 + CE re-ranker > BM25), but it's definitively something we should try ! 

Best,
Thibault
